# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dialog_charge_object.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import QTimer
from PyQt5.QtWidgets import QDialog

class Ui_dialog_charge_object(object):
    def setupUi(self, dialog_charge_object):
        dialog_charge_object.setObjectName("dialog_charge_object")
        self.lbl_charge = QtWidgets.QLabel(dialog_charge_object)
        self.lbl_charge.setGeometry(QtCore.QRect(20, 10, 660, 100))
        font = QtGui.QFont()
        font.setPointSize(50)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_charge.setFont(font)
        self.lbl_charge.setAutoFillBackground(False)
        self.lbl_charge.setStyleSheet("background-color: lightgreen")
        self.lbl_charge.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_charge.setObjectName("lbl_charge")
        self.btn_done = QtWidgets.QPushButton(dialog_charge_object)
        self.btn_done.setGeometry(QtCore.QRect(300, 120, 100, 23))
        self.btn_done.setObjectName("btn_done")

        self.retranslateUi(dialog_charge_object)

    def retranslateUi(self, dialog_charge_object):
        _translate = QtCore.QCoreApplication.translate
        dialog_charge_object.setWindowTitle(_translate("dialog_charge_object", "Charge Object"))
        self.lbl_charge.setText(_translate("dialog_charge_object", "CHARGE"))
        self.btn_done.setText(_translate("dialog_charge_object", "Done"))

class DialogChargeObject(QDialog):

    def __init__(self, parent=None):
        super().__init__(parent)
        self.ui = Ui_dialog_charge_object()
        self.ui.setupUi(self)

        self.parent_instance = parent

        self.ui.btn_done.clicked.connect(self.charge_complete)

        self.timer = QTimer(self)
        self.timer.timeout.connect(self.flash)
        self.timer.start(500)  # Toggle every 500 milliseconds (half a second)

    def charge_complete(self):
        self.timer.stop()
        self.setParent(None)

        self.close()

    def flash(self):
        if self.ui.lbl_charge.styleSheet() == "":
            self.ui.lbl_charge.setStyleSheet("background-color: lightgreen")
        else:
            self.ui.lbl_charge.setStyleSheet("")