# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dialog_com_port.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import QTimer, QSettings
from PyQt5.QtSerialPort import QSerialPort
from PyQt5.QtWidgets import QDialog

from serial.tools import list_ports

class Ui_dialog_com_port(object):
    def setupUi(self, dialog_com_port):
        dialog_com_port.setObjectName("dialog_com_port")
        dialog_com_port.resize(350, 315)
        self.gridLayoutWidget = QtWidgets.QWidget(dialog_com_port)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(20, 30, 311, 266))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.lbl_dev_3 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.lbl_dev_3.setFont(font)
        self.lbl_dev_3.setObjectName("lbl_dev_3")
        self.gridLayout.addWidget(self.lbl_dev_3, 2, 1, 1, 1)
        self.lbl_dev_2 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.lbl_dev_2.setFont(font)
        self.lbl_dev_2.setObjectName("lbl_dev_2")
        self.gridLayout.addWidget(self.lbl_dev_2, 1, 1, 1, 1)
        self.lbl_dev = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.lbl_dev.setFont(font)
        self.lbl_dev.setObjectName("lbl_dev")
        self.gridLayout.addWidget(self.lbl_dev, 0, 1, 1, 1)
        self.lbl_dev_status = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(30)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_dev_status.setFont(font)
        self.lbl_dev_status.setStyleSheet("color: red;")
        self.lbl_dev_status.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_dev_status.setObjectName("lbl_dev_status")
        self.gridLayout.addWidget(self.lbl_dev_status, 0, 0, 1, 1)
        self.cmb_dev_4 = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.cmb_dev_4.setObjectName("cmb_dev_4")
        self.gridLayout.addWidget(self.cmb_dev_4, 3, 2, 1, 1)
        self.lbl_dev_4 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.lbl_dev_4.setFont(font)
        self.lbl_dev_4.setObjectName("lbl_dev_4")
        self.gridLayout.addWidget(self.lbl_dev_4, 3, 1, 1, 1)
        self.cmb_dev = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.cmb_dev.setObjectName("cmb_dev")
        self.gridLayout.addWidget(self.cmb_dev, 0, 2, 1, 1)
        self.cmb_dev_3 = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.cmb_dev_3.setObjectName("cmb_dev_3")
        self.gridLayout.addWidget(self.cmb_dev_3, 2, 2, 1, 1)
        self.cmb_dev_2 = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.cmb_dev_2.setObjectName("cmb_dev_2")
        self.gridLayout.addWidget(self.cmb_dev_2, 1, 2, 1, 1)
        self.lbl_dev_status_3 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(30)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_dev_status_3.setFont(font)
        self.lbl_dev_status_3.setStyleSheet("color: red;")
        self.lbl_dev_status_3.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_dev_status_3.setObjectName("lbl_dev_status_3")
        self.gridLayout.addWidget(self.lbl_dev_status_3, 2, 0, 1, 1)
        self.lbl_dev_status_4 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(30)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_dev_status_4.setFont(font)
        self.lbl_dev_status_4.setStyleSheet("color: red;")
        self.lbl_dev_status_4.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_dev_status_4.setObjectName("lbl_dev_status_4")
        self.gridLayout.addWidget(self.lbl_dev_status_4, 3, 0, 1, 1)
        self.lbl_dev_status_2 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(30)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_dev_status_2.setFont(font)
        self.lbl_dev_status_2.setStyleSheet("color: red;")
        self.lbl_dev_status_2.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_dev_status_2.setObjectName("lbl_dev_status_2")
        self.gridLayout.addWidget(self.lbl_dev_status_2, 1, 0, 1, 1)
        self.lbl_dev_status_5 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(30)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_dev_status_5.setFont(font)
        self.lbl_dev_status_5.setStyleSheet("color: red;")
        self.lbl_dev_status_5.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_dev_status_5.setObjectName("lbl_dev_status_5")
        self.gridLayout.addWidget(self.lbl_dev_status_5, 4, 0, 1, 1)
        self.lbl_dev_5 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.lbl_dev_5.setFont(font)
        self.lbl_dev_5.setObjectName("lbl_dev_5")
        self.gridLayout.addWidget(self.lbl_dev_5, 4, 1, 1, 1)
        self.cmb_dev_5 = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.cmb_dev_5.setObjectName("cmb_dev_5")
        self.gridLayout.addWidget(self.cmb_dev_5, 4, 2, 1, 1)
        self.gridLayoutWidget_2 = QtWidgets.QWidget(dialog_com_port)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(20, 10, 311, 21))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label = QtWidgets.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 0, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 0, 2, 1, 1)

        self.retranslateUi(dialog_com_port)
        QtCore.QMetaObject.connectSlotsByName(dialog_com_port)

    def retranslateUi(self, dialog_com_port):
        _translate = QtCore.QCoreApplication.translate
        dialog_com_port.setWindowTitle(_translate("dialog_com_port", "COM Port Connections"))
        self.lbl_dev_3.setText(_translate("dialog_com_port", "Laser Displacement Sensor"))
        self.lbl_dev_2.setText(_translate("dialog_com_port", "Stepper Controller"))
        self.lbl_dev.setText(_translate("dialog_com_port", "Robotic Arm"))
        self.lbl_dev_status.setText(_translate("dialog_com_port", "•"))
        self.lbl_dev_4.setText(_translate("dialog_com_port", "Feather0"))
        self.lbl_dev_status_3.setText(_translate("dialog_com_port", "•"))
        self.lbl_dev_status_4.setText(_translate("dialog_com_port", "•"))
        self.lbl_dev_status_2.setText(_translate("dialog_com_port", "•"))
        self.lbl_dev_status_5.setText(_translate("dialog_com_port", "•"))
        self.lbl_dev_5.setText(_translate("dialog_com_port", "NIDAQ"))
        self.label.setText(_translate("dialog_com_port", "Status"))
        self.label_3.setText(_translate("dialog_com_port", "COM Port"))


class DialogComPorts(QDialog):

    def __init__(self, port_config, parent=None):
        super().__init__(parent)
        self.ui = Ui_dialog_com_port()
        self.ui.setupUi(self)

        self.parent_instance = parent
        self.port_config = port_config

        self.cmb_list = [self.ui.cmb_dev, self.ui.cmb_dev_2, self.ui.cmb_dev_3, self.ui.cmb_dev_4, self.ui.cmb_dev_5]

        #self.ui.cmb_dev.currentIndexChanged.connect()

        self.refresh_timer = QTimer()
        self.refresh_timer.timeout.connect(self.refresh_ports)
        self.refresh_timer.start(1000) # refresh ports every second

        self.refresh_ports()
        self.load_settings()

    def try_connect(self, port):
        serial = QSerialPort()
        serial.setPortName(selected_port)

        if serial.open(QSerialPort.ReadOnly):
            print(f"Connected to {selected_port}!")
            serial.close()

    def refresh_ports(self):
        available_ports = [port.device for port in list_ports.comports()]

        for cmb in self.cmb_list:
            cmb.clear()
            cmb.addItems(available_ports)

    def save_settings(self):
        settings = QSettings("esd", "ESDApp")
        for index, combo_box in enumerate(self.cmb_list):
            settings.setValue(f"ComboBox{index}", combo_box.currentText())

    def load_settings(self):
        settings = QSettings("esd", "ESDApp")
        for index, combo_box in enumerate(self.cmb_list):
            value = settings.value(f"ComboBox{index}")
            if value is not None:
                combo_box.setCurrentText(value)

    def closeEvent(self, event):
        self.save_settings()  # Save settings when the window is closed