# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dialog_normal_generator.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QDialog
from Src.Controller import Controller
from Src.sim.simhelper import get_normal_point_cloud


class Ui_NormalGenerator(object):
    def setupUi(self, NormalGenerator):
        NormalGenerator.setObjectName("NormalGenerator")
        NormalGenerator.resize(280, 250)
        NormalGenerator.setMinimumSize(QtCore.QSize(280, 250))
        NormalGenerator.setMaximumSize(QtCore.QSize(280, 250))
        self.grp_parameters = QtWidgets.QGroupBox(NormalGenerator)
        self.grp_parameters.setGeometry(QtCore.QRect(10, 20, 261, 161))
        self.grp_parameters.setObjectName("grp_parameters")
        self.formLayoutWidget = QtWidgets.QWidget(self.grp_parameters)
        self.formLayoutWidget.setGeometry(QtCore.QRect(10, 20, 241, 145))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.lbl_info_scan_res = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lbl_info_scan_res.setFont(font)
        self.lbl_info_scan_res.setObjectName("lbl_info_scan_res")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.lbl_info_scan_res)
        self.sbox_scan_resolution = QtWidgets.QDoubleSpinBox(self.formLayoutWidget)
        self.sbox_scan_resolution.setDecimals(0)
        self.sbox_scan_resolution.setMaximum(720.0)
        self.sbox_scan_resolution.setProperty("value", 45.0)
        self.sbox_scan_resolution.setObjectName("sbox_scan_resolution")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.sbox_scan_resolution)
        self.lbl_info_scan_z = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lbl_info_scan_z.setFont(font)
        self.lbl_info_scan_z.setObjectName("lbl_info_scan_z")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.lbl_info_scan_z)
        self.sbox_scan_z = QtWidgets.QDoubleSpinBox(self.formLayoutWidget)
        self.sbox_scan_z.setDecimals(3)
        self.sbox_scan_z.setSingleStep(0.1)
        self.sbox_scan_z.setProperty("value", 1.0)
        self.sbox_scan_z.setObjectName("sbox_scan_z")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.sbox_scan_z)
        self.lbl_info_scan_z_3 = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lbl_info_scan_z_3.setFont(font)
        self.lbl_info_scan_z_3.setObjectName("lbl_info_scan_z_3")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.lbl_info_scan_z_3)
        self.sbox_scan_z_3 = QtWidgets.QDoubleSpinBox(self.formLayoutWidget)
        self.sbox_scan_z_3.setDecimals(3)
        self.sbox_scan_z_3.setSingleStep(0.1)
        self.sbox_scan_z_3.setProperty("value", 1.0)
        self.sbox_scan_z_3.setObjectName("sbox_scan_z_3")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.sbox_scan_z_3)
        self.sbox_probe_distance = QtWidgets.QDoubleSpinBox(self.formLayoutWidget)
        self.sbox_probe_distance.setMinimum(2.5)
        self.sbox_probe_distance.setSingleStep(0.1)
        self.sbox_probe_distance.setProperty("value", 10.0)
        self.sbox_probe_distance.setObjectName("sbox_probe_distance")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.sbox_probe_distance)
        self.lbl_info_probe_distance = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lbl_info_probe_distance.setFont(font)
        self.lbl_info_probe_distance.setObjectName("lbl_info_probe_distance")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.lbl_info_probe_distance)
        self.lbl_z_density = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lbl_z_density.setFont(font)
        self.lbl_z_density.setObjectName("lbl_z_density")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.lbl_z_density)
        self.sbox_scan_z_4 = QtWidgets.QDoubleSpinBox(self.formLayoutWidget)
        self.sbox_scan_z_4.setDecimals(0)
        self.sbox_scan_z_4.setMinimum(1.0)
        self.sbox_scan_z_4.setProperty("value", 1.0)
        self.sbox_scan_z_4.setObjectName("sbox_scan_z_4")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.sbox_scan_z_4)
        self.btn_generate_normals = QtWidgets.QPushButton(NormalGenerator)
        self.btn_generate_normals.setGeometry(QtCore.QRect(10, 200, 261, 23))
        self.btn_generate_normals.setObjectName("btn_generate_normals")

        self.sbox_scan_z.setMaximum(9999)
        self.sbox_scan_z.setProperty("value", 160)
        self.sbox_scan_z_3.setMaximum(9999)
        self.sbox_scan_z_3.setProperty("value", 320)


        self.retranslateUi(NormalGenerator)
        QtCore.QMetaObject.connectSlotsByName(NormalGenerator)

    def retranslateUi(self, NormalGenerator):
        _translate = QtCore.QCoreApplication.translate
        NormalGenerator.setWindowTitle(_translate("NormalGenerator", "Normal Generator"))
        self.grp_parameters.setTitle(_translate("NormalGenerator", "Normal Generation Parameters"))
        self.lbl_info_scan_res.setText(_translate("NormalGenerator", "Points Per Slice"))
        self.lbl_info_scan_z.setText(_translate("NormalGenerator", "Z-min: (mm)"))
        self.lbl_info_scan_z_3.setText(_translate("NormalGenerator", "Z-max: (mm)"))
        self.lbl_info_probe_distance.setText(_translate("NormalGenerator", "Probe Distance (mm):"))
        self.lbl_z_density.setText(_translate("NormalGenerator", "Z-density:"))
        self.btn_generate_normals.setText(_translate("NormalGenerator", "Generate Normals"))


class DialogNormalGenerator(QDialog):

    def __init__(self, parent=None):
        super().__init__(parent)
        self.ui = Ui_NormalGenerator()
        self.ui.setupUi(self)

        self.parent_instance = parent
        self.controller_instance: Controller = parent.controller

        self.ui.btn_generate_normals.clicked.connect(self.generate_normals)

    def generate_normals(self):
        #pts_per_slice, z_limits, z_density, probe_dist, obj_center
        cloud = get_normal_point_cloud(
            int(self.ui.sbox_scan_resolution.text()),
            ((float(self.ui.sbox_scan_z.text()) / 1000) * 2, (float(self.ui.sbox_scan_z_3.text()) / 1000) * 2), # scale correction factor
            int(self.ui.sbox_scan_z_4.text()),
            (float(self.ui.sbox_probe_distance.text()) / 1000) * 2,
            self.controller_instance.simulation_instance.object_offset
        )

        self.controller_instance.simulation_instance.normal_point_cloud = cloud
        self.close()
