# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dialog_probe_helper.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QDialog
from Src.Controller import Controller
from Src.sim import simhelper, sim_constants


class UiDialogProbeHelper(object):

    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(792, 330)
        self.grp_probing_info = QtWidgets.QGroupBox(Dialog)
        self.grp_probing_info.setGeometry(QtCore.QRect(10, 10, 321, 71))
        self.grp_probing_info.setObjectName("grp_probing_info")
        self.lbl_info_probe_points = QtWidgets.QLabel(self.grp_probing_info)
        self.lbl_info_probe_points.setGeometry(QtCore.QRect(10, 17, 81, 24))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lbl_info_probe_points.setFont(font)
        self.lbl_info_probe_points.setObjectName("lbl_info_probe_points")
        self.lbl_info_run_time = QtWidgets.QLabel(self.grp_probing_info)
        self.lbl_info_run_time.setGeometry(QtCore.QRect(10, 37, 101, 24))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lbl_info_run_time.setFont(font)
        self.lbl_info_run_time.setObjectName("lbl_info_run_time")
        self.lbl_probe_points = QtWidgets.QLabel(self.grp_probing_info)
        self.lbl_probe_points.setGeometry(QtCore.QRect(120, 20, 41, 20))
        self.lbl_probe_points.setObjectName("lbl_probe_points")
        self.lbl_runtime = QtWidgets.QLabel(self.grp_probing_info)
        self.lbl_runtime.setGeometry(QtCore.QRect(120, 40, 41, 20))
        self.lbl_runtime.setObjectName("lbl_runtime")
        self.grp_config = QtWidgets.QGroupBox(Dialog)
        self.grp_config.setGeometry(QtCore.QRect(10, 90, 321, 181))
        self.grp_config.setObjectName("grp_config")
        self.btn_gen_normals_2 = QtWidgets.QPushButton(self.grp_config)
        self.btn_gen_normals_2.setGeometry(QtCore.QRect(90, 210, 121, 23))
        self.btn_gen_normals_2.setObjectName("btn_gen_normals_2")
        self.lbl_info_scan_res = QtWidgets.QLabel(self.grp_config)
        self.lbl_info_scan_res.setGeometry(QtCore.QRect(10, 20, 141, 30))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lbl_info_scan_res.setFont(font)
        self.lbl_info_scan_res.setObjectName("lbl_info_scan_res")
        self.lbl_info_scan_z = QtWidgets.QLabel(self.grp_config)
        self.lbl_info_scan_z.setGeometry(QtCore.QRect(10, 50, 141, 30))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lbl_info_scan_z.setFont(font)
        self.lbl_info_scan_z.setObjectName("lbl_info_scan_z")
        self.lbl_info_measure = QtWidgets.QLabel(self.grp_config)
        self.lbl_info_measure.setGeometry(QtCore.QRect(10, 108, 121, 30))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lbl_info_measure.setFont(font)
        self.lbl_info_measure.setObjectName("lbl_info_measure")
        self.sbox_scan_resolution = QtWidgets.QDoubleSpinBox(self.grp_config)
        self.sbox_scan_resolution.setGeometry(QtCore.QRect(160, 26, 91, 20))
        self.sbox_scan_resolution.setMaximum(720.0)
        self.sbox_scan_resolution.setProperty("value", 180.0)
        self.sbox_scan_resolution.setObjectName("sbox_scan_resolution")
        self.sbox_scan_z = QtWidgets.QDoubleSpinBox(self.grp_config)
        self.sbox_scan_z.setGeometry(QtCore.QRect(160, 57, 91, 20))
        self.sbox_scan_z.setProperty("value", 2.0)
        self.sbox_scan_z.setObjectName("sbox_scan_z")
        self.sbox_measure_time = QtWidgets.QDoubleSpinBox(self.grp_config)
        self.sbox_measure_time.setGeometry(QtCore.QRect(160, 115, 91, 20))
        self.sbox_measure_time.setDecimals(0)
        self.sbox_measure_time.setMaximum(1000.0)
        self.sbox_measure_time.setProperty("value", 250.0)
        self.sbox_measure_time.setObjectName("sbox_measure_time")
        self.btn_generate_normals = QtWidgets.QPushButton(self.grp_config)
        self.btn_generate_normals.setGeometry(QtCore.QRect(94, 150, 121, 23))
        self.btn_generate_normals.setObjectName("btn_generate_normals")
        self.lbl_info_probe_distance = QtWidgets.QLabel(self.grp_config)
        self.lbl_info_probe_distance.setGeometry(QtCore.QRect(10, 79, 131, 30))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lbl_info_probe_distance.setFont(font)
        self.lbl_info_probe_distance.setObjectName("lbl_info_probe_distance")
        self.sbox_probe_distance = QtWidgets.QDoubleSpinBox(self.grp_config)
        self.sbox_probe_distance.setGeometry(QtCore.QRect(160, 86, 91, 20))
        self.sbox_probe_distance.setProperty("value", 10.0)
        self.sbox_probe_distance.setObjectName("sbox_probe_distance")
        self.btn_generate_plan = QtWidgets.QPushButton(Dialog)
        self.btn_generate_plan.setEnabled(False)
        self.btn_generate_plan.setGeometry(QtCore.QRect(640, 290, 121, 23))
        self.btn_generate_plan.setObjectName("btn_generate_plan")
        self.list_temp = QtWidgets.QListWidget(Dialog)
        self.list_temp.setGeometry(QtCore.QRect(340, 20, 256, 301))
        self.list_temp.setObjectName("list_temp")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Proper Helper"))
        self.grp_probing_info.setTitle(_translate("Dialog", "Probing Info"))
        self.lbl_info_probe_points.setText(_translate("Dialog", "Probe Points:"))
        self.lbl_info_run_time.setText(_translate("Dialog", "Est. Run Time (s):"))
        self.lbl_probe_points.setText(_translate("Dialog", "0"))
        self.lbl_runtime.setText(_translate("Dialog", "0"))
        self.grp_config.setTitle(_translate("Dialog", "Configuration"))
        self.lbl_info_scan_res.setText(_translate("Dialog", "Normal Resoultion (Deg):"))
        self.lbl_info_scan_z.setText(_translate("Dialog", "Normal Z Density (mm):"))
        self.lbl_info_measure.setText(_translate("Dialog", "Measure Time (ms):"))
        self.btn_generate_normals.setText(_translate("Dialog", "Generate Normals"))
        self.lbl_info_probe_distance.setText(_translate("Dialog", "Probe Distance (mm):"))
        self.btn_generate_plan.setText(_translate("Dialog", "Generate Probe Plan"))


class DialogProbeHelper(QDialog):

    def __init__(self, parent=None):
        super().__init__(parent)
        self.ui = UiDialogProbeHelper()
        self.ui.setupUi(self)

        self.parent_instance = parent
        self.controller_instance: Controller = parent.controller

        self.ui.btn_generate_normals.clicked.connect(self.generate_normals)

    def generate_normals(self):
        cloud = simhelper.get_object_point_cloud(
            probe_dist=(float(self.ui.sbox_probe_distance.text())/1000)*sim_constants.SIM_SCALE,
            resolution=(int(float(self.ui.sbox_scan_resolution.text()))),
            z_density=(int(float(self.ui.sbox_scan_z.text()))*sim_constants.SIM_SCALE)*10
        )

        if self.controller_instance.simulation_instance.current_point_cloud is not None:
            self.controller_instance.simulation_instance.current_point_cloud.delete_cloud()
            self.controller_instance.simulation_instance.current_point_cloud = None

        self.controller_instance.simulation_instance.current_point_cloud = cloud

        self.ui.lbl_probe_points.setText(str(cloud.get_num_points()))
