# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dialog_obj_offset.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import os
import time

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QDialog

DATA_DIR = os.path.join(os.path.abspath('../'), "Data", "sim")
URDF_PLAT = os.path.join(DATA_DIR, "urdf", "actuated_platform_no_obj.urdf")


class UIDialogObjectOffset(object):
    def setupUi(self, dialog_obj_offset):
        dialog_obj_offset.setObjectName("dialog_obj_offset")
        dialog_obj_offset.resize(529, 95)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        dialog_obj_offset.setFont(font)
        self.buttonBox = QtWidgets.QDialogButtonBox(dialog_obj_offset)
        self.buttonBox.setGeometry(QtCore.QRect(440, 10, 81, 241))
        self.buttonBox.setOrientation(QtCore.Qt.Vertical)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel | QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.grp_manual = QtWidgets.QGroupBox(dialog_obj_offset)
        self.grp_manual.setGeometry(QtCore.QRect(20, 20, 351, 51))
        self.grp_manual.setObjectName("grp_manual")
        self.lbl_info_m1 = QtWidgets.QLabel(self.grp_manual)
        self.lbl_info_m1.setEnabled(True)
        self.lbl_info_m1.setGeometry(QtCore.QRect(90, 20, 31, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lbl_info_m1.setFont(font)
        self.lbl_info_m1.setObjectName("lbl_info_m1")
        self.txt_obj_a = QtWidgets.QDoubleSpinBox(self.grp_manual)
        self.txt_obj_a.setEnabled(True)
        self.txt_obj_a.setGeometry(QtCore.QRect(24, 17, 62, 22))
        self.txt_obj_a.setObjectName("txt_obj_a")
        self.label = QtWidgets.QLabel(self.grp_manual)
        self.label.setGeometry(QtCore.QRect(8, 20, 16, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.grp_manual)
        self.label_2.setGeometry(QtCore.QRect(120, 20, 16, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.lbl_info_m1_2 = QtWidgets.QLabel(self.grp_manual)
        self.lbl_info_m1_2.setEnabled(True)
        self.lbl_info_m1_2.setGeometry(QtCore.QRect(202, 20, 31, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lbl_info_m1_2.setFont(font)
        self.lbl_info_m1_2.setObjectName("lbl_info_m1_2")
        self.txt_obj_a_2 = QtWidgets.QDoubleSpinBox(self.grp_manual)
        self.txt_obj_a_2.setEnabled(True)
        self.txt_obj_a_2.setGeometry(QtCore.QRect(136, 17, 62, 22))
        self.txt_obj_a_2.setObjectName("txt_obj_a_2")
        self.txt_obj_a_3 = QtWidgets.QDoubleSpinBox(self.grp_manual)
        self.txt_obj_a_3.setEnabled(False)
        self.txt_obj_a_3.setGeometry(QtCore.QRect(254, 17, 62, 22))
        self.txt_obj_a_3.setObjectName("txt_obj_a_3")
        self.lbl_info_m1_3 = QtWidgets.QLabel(self.grp_manual)
        self.lbl_info_m1_3.setEnabled(True)
        self.lbl_info_m1_3.setGeometry(QtCore.QRect(320, 20, 31, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lbl_info_m1_3.setFont(font)
        self.lbl_info_m1_3.setObjectName("lbl_info_m1_3")
        self.label_3 = QtWidgets.QLabel(self.grp_manual)
        self.label_3.setGeometry(QtCore.QRect(238, 20, 16, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")

        self.retranslateUi(dialog_obj_offset)
        self.buttonBox.accepted.connect(dialog_obj_offset.accept)  # type: ignore
        self.buttonBox.rejected.connect(dialog_obj_offset.reject)  # type: ignore
        QtCore.QMetaObject.connectSlotsByName(dialog_obj_offset)

    def retranslateUi(self, dialog_obj_offset):
        _translate = QtCore.QCoreApplication.translate
        dialog_obj_offset.setWindowTitle(_translate("dialog_obj_offset", "Dialog"))
        self.grp_manual.setTitle(_translate("dialog_obj_offset", "Manual Offsets"))
        self.lbl_info_m1.setText(_translate("dialog_obj_offset", "mm"))
        self.label.setText(_translate("dialog_obj_offset", "X"))
        self.label_2.setText(_translate("dialog_obj_offset", "Y"))
        self.lbl_info_m1_2.setText(_translate("dialog_obj_offset", "mm"))
        self.lbl_info_m1_3.setText(_translate("dialog_obj_offset", "mm"))
        self.label_3.setText(_translate("dialog_obj_offset", "Z"))


class DialogOffsetObject(QDialog):

    def __init__(self, parent=None):
        super().__init__(parent)
        self.ui = UIDialogObjectOffset()
        self.ui.setupUi(self)

        self.parent_instance = parent
        self.ui.buttonBox.clicked.connect(self.on_done)

    def on_done(self):
        (x, y, z) = (float(self.ui.txt_obj_a.text()) / 1000,
                     float(self.ui.txt_obj_a_2.text()) / 1000, float(self.ui.txt_obj_a_3.text()) / 1000)
        URDF_OFFSET_LINE_NUM = 77

        with open(URDF_PLAT, 'r') as file:
            content = file.readlines()
            str_write = f'    <origin xyz="{x} {y} 0.175"/>\n'
            content[URDF_OFFSET_LINE_NUM - 1] = str_write  # replace contents with modified offset.

        with open(URDF_PLAT, 'w') as file:
            file.writelines(content)

        # Now that offset is written to urdf, reload it!
        print("[MAIN] Sending object to simulation! Please hold...")
        self.parent_instance.o3d_visualizer.pack_object()
        time.sleep(0.5)
        self.parent_instance.controller.restart_sim()
