# -*- coding: utf-8 -*-
import pybullet as p
# Form implementation generated from reading ui file 'dialog_choose_object.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QDialog, QFileDialog
from src.sim.simulation import URDF_PLAT
from src.gui.gui_consts import *

import os
import shutil

class UiDialogChooseObject(object):
    def setupUi(self, dialog_choose_object):
        dialog_choose_object.setObjectName("dialog_choose_object")
        dialog_choose_object.resize(368, 92)
        dialog_choose_object.setMinimumSize(QtCore.QSize(368, 92))
        dialog_choose_object.setMaximumSize(QtCore.QSize(368, 92))
        self.input_filename = QtWidgets.QLineEdit(dialog_choose_object)
        self.input_filename.setGeometry(QtCore.QRect(10, 20, 251, 21))
        self.input_filename.setObjectName("input_filename")
        self.btn_browse = QtWidgets.QPushButton(dialog_choose_object)
        self.btn_browse.setGeometry(QtCore.QRect(280, 20, 75, 23))
        self.btn_browse.setObjectName("btn_browse")
        self.btn_submit = QtWidgets.QPushButton(dialog_choose_object)
        self.btn_submit.setGeometry(QtCore.QRect(280, 50, 75, 23))
        self.btn_submit.setObjectName("btn_submit")
        self.chk_vhacd = QtWidgets.QCheckBox(dialog_choose_object)
        self.chk_vhacd.setGeometry(QtCore.QRect(10, 50, 81, 17))
        self.chk_vhacd.setChecked(True)
        self.chk_vhacd.setObjectName("chk_vhacd")

        self.retranslateUi(dialog_choose_object)
        QtCore.QMetaObject.connectSlotsByName(dialog_choose_object)

    def retranslateUi(self, dialog_choose_object):
        _translate = QtCore.QCoreApplication.translate
        dialog_choose_object.setWindowTitle(_translate("dialog_choose_object", "Dialog"))
        self.btn_browse.setText(_translate("dialog_choose_object", "Browse"))
        self.btn_submit.setText(_translate("dialog_choose_object", "Submit"))
        self.chk_vhacd.setText(_translate("dialog_choose_object", "Generate V-HACD?"))

class DialogChooseObject(QDialog):

    def __init__(self, parent=None):
        super().__init__(parent)
        self.ui = UiDialogChooseObject()
        self.ui.setupUi(self)

        self.parent_instance = parent
        self.controller_instance = parent.controller

        self.ui.btn_browse.clicked.connect(self.browse)
        self.ui.btn_submit.clicked.connect(self.submit)


    def browse(self):
        fname = QFileDialog.getOpenFileName(self, 'Open File', os.path.abspath('../..'))
        self.ui.input_filename.setText(fname[0])


    def submit(self):
        input_dir = self.ui.input_filename.text()  # this will also be the .obj for visual

        if self.ui.chk_vhacd.isChecked():
            print("[MAIN] Generating V-HACD... this will take some time.")
            time.sleep(1)
            output_name = "imported_object-vhacd.obj"
            p.vhacd(input_dir, output_name,
                    "vhacd_log.txt", resolution=10000000)

            shutil.move(output_name, os.path.join(OBJECT_DIR, output_name))
            shutil.move("vhacd_log.txt", os.path.join(GENERATED_DIR, "vhacd_log.txt"))

        shutil.copy(input_dir, os.path.join(OBJECT_DIR, "imported_object.obj"))
